project:
  type: website

website:
  title: "R course"
  navbar:
    left:
      - href: index.qmd
        text: Slides 
      - Exercises.qmd
      - Solutions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



